spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      port: 27017
      host: ${MONGO_HOST:127.0.0.1}
      database: demo
      repositories:
        type: auto
cors:
  originPatterns:  ${CORS_PATTERN:http://localhost:4200}